hibernate:
  ddl-auto:
    mode: update

spring:
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
  datasource:
    url: <connection string here>
      username: <username>
      password: <password>
    driver-class-name: org.postgresql.Driver